### ISSUE TITLE
hexo报错ERROR The upstream repository of theme NexT has been changed.

### ISSUE THREAD

**Issue by linwhitehat** [guanqr/blog#38]
大佬，最近想试试新版的next主题，然后升级了一下hexo和插件，之后修改了一些主题样式，结果在执行`hexo g`时显示这样的错误：
```
ERROR The upstream repository of theme NexT has been changed.
ERROR For more information: https://github.com/next-theme/hexo-theme-next
ERROR Documentation: https://theme-next.js.org
```
一开始以为是hexo的版本问题，在改回原来版本时仍然报错，大佬有什么解决办法吗？
目前的next版本是7.7.0，hexo-cli版本是3.1.0，hexo版本是4.2.1，具体插件版本信息如下：
```
$ hexo -version
hexo: 4.2.1
hexo-cli: 3.1.0
os: Windows_NT 10.0.19041 win32 x64
node: 12.18.2
v8: 7.8.279.23-node.39
uv: 1.38.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.16.0
modules: 72
nghttp2: 1.41.0
napi: 6
llhttp: 2.0.4
http_parser: 2.9.3
openssl: 1.1.1g
cldr: 37.0
icu: 67.1
tz: 2019c
unicode: 13.0
```

**Comment by guanqr** [comment]
@linwhitehat 现在 NexT 主题重新创建了一个仓库，是 v8 版本的，报错的信息中提示的这个仓库就是新仓库的地址：

```
ERROR For more information: https://github.com/next-theme/hexo-theme-next
```

可能是为了提示用户想要升级主题要到新的仓库中吧

**Comment by linwhitehat** [comment]
> @linwhitehat 现在 NexT 主题重新创建了一个仓库，是 v8 版本的，报错的信息中提示的这个仓库就是新仓库的地址：
> 
> ```
> ERROR For more information: https://github.com/next-theme/hexo-theme-next
> ```
> 
> 可能是为了提示用户想要升级主题要到新的仓库中吧

嗯嗯，我知道出了新版本，但是在v8的仓库下提了issue询问，维护人员说他也不清楚这个原因，而且在提交更新到仓库后，还莫名报了leancloud的错误，看了一下阅读统计好像也正常，也没修改leancloud的配置，报错的是之前为了解决leancloud的安全问题安装的插件`leancloud_counter_security_sync`，具体报错信息如下：
```
INFO  Deploying: leancloud_counter_security_sync
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
TypeError: serverURL option is required for apps from CN region
    at Object.init (E:\Git_repository\blog\hexo\node_modules\leancloud-storage\dist\node\init.js:99:13)
    at Hexo.sync (E:\Git_repository\blog\hexo\node_modules\hexo-leancloud-counter-security\index.js:86:8)
    at Hexo.tryCatcher (E:\Git_repository\blog\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (E:\Git_repository\blog\hexo\node_modules\bluebird\js\release\method.js:15:34)
    at E:\Git_repository\blog\hexo\node_modules\hexo\lib\plugins\console\deploy.js:53:20
    at tryCatcher (E:\Git_repository\blog\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Object.gotValue (E:\Git_repository\blog\hexo\node_modules\bluebird\js\release\reduce.js:166:18)
    at Object.gotAccum (E:\Git_repository\blog\hexo\node_modules\bluebird\js\release\reduce.js:155:25)
    at Object.tryCatcher (E:\Git_repository\blog\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\Git_repository\blog\hexo\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\Git_repository\blog\hexo\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\Git_repository\blog\hexo\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\Git_repository\blog\hexo\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (E:\Git_repository\blog\hexo\node_modules\bluebird\js\release\promise.js:673:18)
    at Promise._resolveCallback (E:\Git_repository\blog\hexo\node_modules\bluebird\js\release\promise.js:466:57)
    at Promise._settlePromiseFromHandler (E:\Git_repository\blog\hexo\node_modules\bluebird\js\release\promise.js:559:17)
    at Promise._settlePromise (E:\Git_repository\blog\hexo\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\Git_repository\blog\hexo\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\Git_repository\blog\hexo\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (E:\Git_repository\blog\hexo\node_modules\bluebird\js\release\promise.js:673:18)
    at Promise._resolveCallback (E:\Git_repository\blog\hexo\node_modules\bluebird\js\release\promise.js:489:14)
    at Promise._settlePromiseFromHandler (E:\Git_repository\blog\hexo\node_modules\bluebird\js\release\promise.js:559:17)
    at Promise._settlePromise (E:\Git_repository\blog\hexo\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\Git_repository\blog\hexo\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\Git_repository\blog\hexo\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (E:\Git_repository\blog\hexo\node_modules\bluebird\js\release\promise.js:673:18)
    at Promise._resolveCallback (E:\Git_repository\blog\hexo\node_modules\bluebird\js\release\promise.js:466:57)
    at ReductionPromiseArray._resolve (E:\Git_repository\blog\hexo\node_modules\bluebird\js\release\reduce.js:60:19)
    at Promise.completed [as _fulfillmentHandler0] (E:\Git_repository\blog\hexo\node_modules\bluebird\js\release\reduce.js:133:15)
    at Promise._settlePromise (E:\Git_repository\blog\hexo\node_modules\bluebird\js\release\promise.js:601:21)
    at Promise._settlePromise0 (E:\Git_repository\blog\hexo\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\Git_repository\blog\hexo\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (E:\Git_repository\blog\hexo\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (E:\Git_repository\blog\hexo\node_modules\bluebird\js\release\async.js:86:9)

```

**Comment by guanqr** [comment]
这我就不太清楚了。leancloud 这个提示的是需要填写 serverURL 的内容？要是 leancloud 服务器选择的是国内的话需要绑定一个域名的。

**Comment by linwhitehat** [comment]
我没有变更节点选择，我使用的是国内版的leancloud，用的开发版提示不需要绑定域名/(ㄒoㄒ)/~~现在也不知道啥情况
